# CMake generated Testfile for 
# Source directory: /cluster/2020shachem/CSL/nestCompile9/nest-simulator-2.14.0/testsuite/mpitests
# Build directory: /cluster/2020shachem/CSL/nestCompile9/nest-simulator-2.14.0/testsuite/mpitests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(mpitests/issue-281.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/issue-281.sli")
add_test(mpitests/issue-600.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/issue-600.sli")
add_test(mpitests/test_all_to_all.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_all_to_all.sli")
add_test(mpitests/test_connect_array_all_to_all_mpi.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_connect_array_all_to_all_mpi.sli")
add_test(mpitests/test_connect_array_fixed_indegree_mpi.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_connect_array_fixed_indegree_mpi.sli")
add_test(mpitests/test_connect_array_fixed_outdegree_mpi.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_connect_array_fixed_outdegree_mpi.sli")
add_test(mpitests/test_delay_exchange.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_delay_exchange.sli")
add_test(mpitests/test_fixed_indegree.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_fixed_indegree.sli")
add_test(mpitests/test_gamma_sup_generator.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_gamma_sup_generator.sli")
add_test(mpitests/test_gap_junctions_mpi.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_gap_junctions_mpi.sli")
add_test(mpitests/test_get_node_fncs.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_get_node_fncs.sli")
add_test(mpitests/test_getrng_Vmset.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_getrng_Vmset.sli")
add_test(mpitests/test_getrng_neuron.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_getrng_neuron.sli")
add_test(mpitests/test_ginzburg_neuron.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_ginzburg_neuron.sli")
add_test(mpitests/test_global_rng.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_global_rng.sli")
add_test(mpitests/test_gsd.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_gsd.sli")
add_test(mpitests/test_gsd_FixedTotalNumber.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_gsd_FixedTotalNumber.sli")
add_test(mpitests/test_gsd_distribution.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_gsd_distribution.sli")
add_test(mpitests/test_gsd_distribution_threaded.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_gsd_distribution_threaded.sli")
add_test(mpitests/test_gsd_threaded.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_gsd_threaded.sli")
add_test(mpitests/test_iaf_ring.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_iaf_ring.sli")
add_test(mpitests/test_mini_brunel_ps.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_mini_brunel_ps.sli")
add_test(mpitests/test_mip_generator.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_mip_generator.sli")
add_test(mpitests/test_neuron_vp.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_neuron_vp.sli")
add_test(mpitests/test_noise_generator.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_noise_generator.sli")
add_test(mpitests/test_one_to_one.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_one_to_one.sli")
add_test(mpitests/test_pairwise_bernoulli.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_pairwise_bernoulli.sli")
add_test(mpitests/test_parallel_conn_and_rand.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_parallel_conn_and_rand.sli")
add_test(mpitests/test_poisson_generator.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_poisson_generator.sli")
add_test(mpitests/test_poisson_generator_ps.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_poisson_generator_ps.sli")
add_test(mpitests/test_pp_psc_delta.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_pp_psc_delta.sli")
add_test(mpitests/test_ppd_sup_generator.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_ppd_sup_generator.sli")
add_test(mpitests/test_pulsepacket_generator.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_pulsepacket_generator.sli")
add_test(mpitests/test_rate_neurons_mpi.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_rate_neurons_mpi.sli")
add_test(mpitests/test_sinusoidal_gamma_generator_1.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_gamma_generator_1.sli")
add_test(mpitests/test_sinusoidal_gamma_generator_2.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_gamma_generator_2.sli")
add_test(mpitests/test_sinusoidal_gamma_generator_3.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_gamma_generator_3.sli")
add_test(mpitests/test_sinusoidal_gamma_generator_4.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_gamma_generator_4.sli")
add_test(mpitests/test_sinusoidal_poisson_generator_1.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_poisson_generator_1.sli")
add_test(mpitests/test_sinusoidal_poisson_generator_2.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_poisson_generator_2.sli")
add_test(mpitests/test_sinusoidal_poisson_generator_3.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_poisson_generator_3.sli")
add_test(mpitests/test_sinusoidal_poisson_generator_4.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_poisson_generator_4.sli")
add_test(mpitests/test_sinusoidal_poisson_generator_5.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_poisson_generator_5.sli")
add_test(mpitests/test_sinusoidal_poisson_generator_6.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_sinusoidal_poisson_generator_6.sli")
add_test(mpitests/test_symmetric_connections_mpi.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/test_symmetric_connections_mpi.sli")
add_test(mpitests/ticket-336-mpi.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/ticket-336-mpi.sli")
add_test(mpitests/ticket-400.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/ticket-400.sli")
add_test(mpitests/ticket-460.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/ticket-460.sli")
add_test(mpitests/ticket-955.sli "/cluster/2020shachem/nestInstall/bin/nest_indirect" "/cluster/2020shachem/nestInstall/share/doc/nest/mpitests/ticket-955.sli")
