#! /bin/sh

prefix=${NEST_INSTALL_DIR:-/cluster/2020shachem/nestInstall7}
exec_prefix=${prefix}

usage()
{
    cat <<EOF
Usage: nest-config [OPTION]

Known values for OPTION are:

  --prefix              NEST install prefix for architecture-independent files
  --exec-prefix         NEST install prefix for architecture-dependent files
  --libs                print library linking information
  --cflags              print pre-processor and compiler flags
  --includes            print includes
  --compiler            print the compiler used to compile NEST
  --static-libraries    print "ON" if configured for static libraries, "OFF" otherwise
  --docdir              print the relative path (to prefix) to the installed documentation
  --datadir             print the relative path (to prefix) to the installed data
  --libdir              print the relative path (to prefix) to the installed libraries
  --help                display this help and exit
  --version             output version information

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
        prefix=$optarg
        ;;
    --prefix)
        echo $prefix
        ;;
    --exec-prefix)
        echo $exec_prefix
        ;;
    --version)
        echo "2.14.0"
        ;;
    --help)
        usage 0
        ;;
    --includes)
        echo " -I/cluster/2020shachem/CSL/nestCompile7/nest-simulator-2.14.0/libnestutil -I/cluster/2020shachem/CSL/nestCompile7/libnestutil -I/cluster/2020shachem/CSL/nestCompile7/nest-simulator-2.14.0/librandom -I/cluster/2020shachem/CSL/nestCompile7/nest-simulator-2.14.0/sli -I/cluster/2020shachem/CSL/nestCompile7/nest-simulator-2.14.0/topology -I/cluster/2020shachem/CSL/nestCompile7/nest-simulator-2.14.0/nestkernel -I/cluster/2020shachem/CSL/nestCompile7/nest-simulator-2.14.0/nest -I/usr/include -I/usr/lib64/openmpi-3.0.0/include"
        ;;
    --cflags)
        echo " -O2 -Wall -fopenmp  "
        ;;
    --libs)
        echo "-L$prefix/lib64 -lnestutil -lnest -lrandom -lsli -lnestkernel -fopenmp LTDL_LIBRARIES-NOTFOUND /lib64/libreadline.so /lib64/libncurses.so    /usr/lib64/openmpi-3.0.0/lib/libmpi.so"
        ;;
    --compiler)
        echo "/usr/bin/c++"
        ;;

    --static-libraries)
        echo "OFF"
        ;;
    --docdir)
        echo "share/doc/nest"
        ;;
    --datadir)
        echo "share/nest"
        ;;
    --libdir)
        echo "lib64"
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done

exit 0
